"""Core data contracts for ARGUS research pipeline.

Evidence-first traceability backbone:
    Report -> Claim -> Evidence -> Source
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.core.provenance import compute_content_hash


class SourceType(str, Enum):
    WEB = "web"
    ACADEMIC = "academic"
    DOCUMENT = "document"
    DATABASE = "database"
    USER = "user"
    OTHER = "other"


class VerificationStatus(str, Enum):
    """Status outcomes from verification phase."""

    VERIFIED = "verified"    # evidence adequately supports claim
    REJECTED = "rejected"    # evidence contradicts / does not support claim
    UNCERTAIN = "uncertain"  # evidence is insufficient to decide


class ResearchQuestion(BaseModel):
    """Initial research question posed to ARGUS."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str = Field(min_length=5, description="The user's original research question.")
    domain: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Planner agent."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    research_question_id: Optional[str] = None
    topic: str
    key_questions: List[str] = Field(default_factory=list)
    sub_questions: List[str] = Field(default_factory=list)
    information_needed: List[str] = Field(default_factory=list)
    initial_hypotheses: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def sync_questions(self) -> "ResearchPlan":
        """Keep key_questions and sub_questions in sync if only one is provided."""
        if self.key_questions and not self.sub_questions:
            self.sub_questions = list(self.key_questions)
        elif self.sub_questions and not self.key_questions:
            self.key_questions = list(self.sub_questions)
        return self


class Source(BaseModel):
    """Provenance details for retrieved information."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    url: Optional[str] = None
    title: str
    source_type: SourceType | str = SourceType.WEB
    page_text: Optional[str] = None
    content_hash: Optional[str] = None
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def auto_hash_content(self) -> "Source":
        """Compute SHA-256 content hash if page_text is provided without hash."""
        if self.page_text and not self.content_hash:
            self.content_hash = compute_content_hash(self.page_text)
        return self


class Evidence(BaseModel):
    """A direct extract from a Source supporting a Claim.

    `quote` must be verbatim text from the source — not an LLM-generated
    summary. This distinction matters for Verifier checks later.
    IDs and timestamps are always system-generated, never from the LLM.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source_id: str                                        # FK → Source.id
    quote: str                                            # verbatim extract
    relevance: float = Field(default=1.0, ge=0.0, le=1.0)
    page: Optional[int] = None
    location: Optional[str] = None
    is_verbatim: bool = True                              # verified deterministically
    match_score: float = Field(default=1.0, ge=0.0, le=1.0)


class Claim(BaseModel):
    """A factual statement extracted from research, backed by one or more Evidence items.

    IDs are always system-generated. The LLM provides only:
      - claim_text
      - confidence
    Evidence linkage is assembled by Python after extraction.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    claim_text: str
    evidence_ids: List[str] = Field(default_factory=list)  # FK list → Evidence.id
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)


class ResearchResult(BaseModel):
    """The complete output of the Researcher agent for a given ResearchPlan.

    This is the research artifact passed to the Verifier. Traceability chain:
        claims[i].evidence_ids → evidence[j].source_id → sources[k].url

    All IDs and timestamps are system-generated; the LLM provides only content.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    research_plan_id: str                          # FK → ResearchPlan.id
    sources: List[Source] = Field(default_factory=list)
    evidence: List[Evidence] = Field(default_factory=list)
    claims: List[Claim] = Field(default_factory=list)
    quote_fidelity: float = Field(default=1.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def compute_quote_fidelity(self) -> "ResearchResult":
        """Compute Quote Fidelity = valid_extracted_quotes / total_extracted_quotes."""
        if self.evidence:
            valid_count = sum(1 for e in self.evidence if e.is_verbatim)
            self.quote_fidelity = round(valid_count / len(self.evidence), 4)
        else:
            self.quote_fidelity = 1.0
        return self


class VerificationResult(BaseModel):
    """Independent verification verdict evaluating a Claim against its Evidence."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    claim_id: str
    status: VerificationStatus
    supported: bool = False
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    reasoning: str = ""
    evidence_ids: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="before")
    @classmethod
    def normalize_status_and_reason(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # Normalize legacy and case-insensitive status strings
            st = data.get("status")
            if isinstance(st, str):
                st_lower = st.lower().strip()
                if st_lower in ("valid", "verified", "pass"):
                    data["status"] = VerificationStatus.VERIFIED
                elif st_lower in ("invalid", "rejected", "fail"):
                    data["status"] = VerificationStatus.REJECTED
                elif st_lower in ("partial", "unverifiable", "uncertain"):
                    data["status"] = VerificationStatus.UNCERTAIN
            # Backwards compatibility: allow 'reason' to populate 'reasoning'
            if "reason" in data and "reasoning" not in data:
                data["reasoning"] = data["reason"]
        return data

    @model_validator(mode="after")
    def sync_supported_flag(self) -> "VerificationResult":
        """Keep `supported` aligned with status."""
        self.supported = (self.status == VerificationStatus.VERIFIED)
        return self


class VerificationReport(BaseModel):
    """Aggregated verification results for an entire ResearchResult."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    research_result_id: str
    results: List[VerificationResult] = Field(default_factory=list)
    verified_count: int = 0
    rejected_count: int = 0
    uncertain_count: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def compute_counts(self) -> "VerificationReport":
        self.verified_count = sum(1 for r in self.results if r.status == VerificationStatus.VERIFIED)
        self.rejected_count = sum(1 for r in self.results if r.status == VerificationStatus.REJECTED)
        self.uncertain_count = sum(1 for r in self.results if r.status == VerificationStatus.UNCERTAIN)
        return self


class Report(BaseModel):
    """Final research report synthesizing verified claims."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    research_question_id: str
    content: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    claim_ids: List[str] = Field(default_factory=list)
    source_ids: List[str] = Field(default_factory=list)